# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3c410ea0755a4e12a3d1fde9a2533189822700e7f56e35567dd4b1af0c14cf71ef1e342ce65c79629d1e493a3b162b8fb479dabcd3dd362742cff4143892f1

test:
  secret_key_base: 68df8f237a160b1a4e1a27d521b00009096ca2423abe541cb0c91db4ceacd827939816e023adcbd5ce0bd32ca7f14972224e6af60b5d7a47bb24a37393f5104c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
